/*
# Part 1: Additional Instructors

Adding 14 more instructors to reach 20 total instructors.
Each instructor has multilingual name, bio, avatar, credentials, and specializations.
*/

INSERT INTO instructors (name, bio, avatar_url, credentials, specializations, verified, website, social_links) VALUES
('{"en": "Sarah Johnson", "fr": "Sarah Johnson", "ar": "سارة جونسون"}', '{"en": "Professional fashion designer with over 10 years of experience in pattern making and garment construction. Specializing in creating detailed, easy-to-follow patterns for all skill levels.", "fr": "Designer de mode professionnelle avec plus de 10 ans d''expérience dans la création de patrons et la construction de vêtements.", "ar": "مصممة أزياء محترفة مع أكثر من 10 سنوات من الخبرة في صناعة الأنماط وتصميم الملابس."}', 'https://images.pexels.com/photos/7801000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Certified Pattern Maker', 'Fashion Design Instructor', 'Sewing Expert'], ARRAY['dresses', 'evening wear', 'bridal'], true, 'https://example.com/instructor-sarah', '{"instagram": "https://instagram.com/sarahdesigns", "youtube": "https://youtube.com/sarahjohnson", "pinterest": "https://pinterest.com/sarahpatterns"}'::jsonb),
('{"en": "Emma Wilson", "fr": "Emma Wilson", "ar": "إيما ويلسون"}', '{"en": "Expert in menswear and tailored garments with a passion for traditional craftsmanship.", "fr": "Experte en vêtements masculins et tailoring avec une passion pour l''artisanat traditionnel.", "ar": "خبيرة في ملابس الرجال والتفصيل مع شغف بالحرف اليدوية التقليدية."}', 'https://images.pexels.com/photos/7802000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Master Tailor', 'Menswear Specialist'], ARRAY['menswear', 'suits', 'formal wear'], false, 'https://example.com/instructor-emma', '{"instagram": "https://instagram.com/emmawilson", "youtube": "https://youtube.com/emmacreates"}'::jsonb),
('{"en": "Olivia Martinez", "fr": "Olivia Martinez", "ar": "أوليفيا مارتينيز"}', '{"en": "Childrenswear designer creating adorable and comfortable patterns for little ones.", "fr": "Designer de mode enfantine créant des patrons adorables et confortables pour les petits.", "ar": "مصممة ملابس أطفال تنشئ أنماط لطيفة ومريحة للصغار."}', 'https://images.pexels.com/photos/7803000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Childrenswear Expert', 'Safety Standards Certified'], ARRAY['childrenswear', 'baby clothes', 'playwear'], true, 'https://example.com/instructor-olivia', '{"instagram": "https://instagram.com/oliviamartinez"}'::jsonb),
('{"en": "Sophia Chen", "fr": "Sophia Chen", "ar": "صوفيا تشن"}', '{"en": "Accessory designer specializing in bags, hats, and fashion accessories.", "fr": "Designer d''accessoires spécialisée dans les sacs, chapeaux et accessoires de mode.", "ar": "مصممة إكسسوارات متخصصة في الحقائب والقبعات وإكسسوارات الأزياء."}', 'https://images.pexels.com/photos/7804000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Accessory Designer', 'Leather Worker'], ARRAY['accessories', 'bags', 'hats'], true, 'https://example.com/instructor-sophia', '{"instagram": "https://instagram.com/sophiachen", "pinterest": "https://pinterest.com/sophiaaccessories"}'::jsonb),
('{"en": "Isabella Rodriguez", "fr": "Isabella Rodriguez", "ar": "إيزابيلا رودريغيز"}', '{"en": "Traditional and cultural wear specialist with expertise in abayas, kaftans, and modest fashion.", "fr": "Spécialiste des vêtements traditionnels et culturels, experte en abayas et caftans.", "ar": "متخصصة في الملابس التقليدية والثقافية مع خبرة في العبايات والقفطانات والموضة المحتشمة."}', 'https://images.pexels.com/photos/7805000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Traditional Wear Expert', 'Cultural Fashion Designer'], ARRAY['traditional', 'abayas', 'kaftans'], true, 'https://example.com/instructor-isabella', '{"instagram": "https://instagram.com/isabellarodriguez"}'::jsonb),
('{"en": "Mia Thompson", "fr": "Mia Thompson", "ar": "ميا طومسون"}', '{"en": "Activewear and sportswear designer creating comfortable and functional patterns.", "fr": "Designer de vêtements de sport créant des patrons confortables et fonctionnels.", "ar": "مصممة ملابس رياضية ونشطة تنشئ أنماط مريحة وعملية."}', 'https://images.pexels.com/photos/7806000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Activewear Specialist', 'Performance Fabrics Expert'], ARRAY['sportswear', 'activewear', 'loungewear'], false, 'https://example.com/instructor-mia', '{"instagram": "https://instagram.com/miathompson", "youtube": "https://youtube.com/miaactivewear"}'::jsonb),
('{"en": "Charlotte Davis", "fr": "Charlotte Davis", "ar": "شارلوت ديفيس"}', '{"en": "Lingerie and intimate apparel designer with delicate and beautiful creations.", "fr": "Designer de lingerie créant des pièces délicates et magnifiques.", "ar": "مصممة ملابس داخلية وملابس حميمية تنشئ قطع رقيقة وجميلة."}', 'https://images.pexels.com/photos/7807000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Lingerie Specialist', 'Lace Expert'], ARRAY['lingerie', 'sleepwear', 'intimates'], true, 'https://example.com/instructor-charlotte', '{"instagram": "https://instagram.com/charlottedavis"}'::jsonb),
('{"en": "Amelia Garcia", "fr": "Amelia Garcia", "ar": "أميليا غارسيا"}', '{"en": "Outerwear specialist creating coats, jackets, and weather-appropriate garments.", "fr": "Spécialiste des vêtements d''extérieur créant manteaux et vestes.", "ar": "متخصصة في الملابس الخارجية تنشئ المعاطف والجاكيتات."}', 'https://images.pexels.com/photos/7808000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Outerwear Expert', 'Coat Construction Specialist'], ARRAY['outerwear', 'coats', 'jackets'], false, 'https://example.com/instructor-amelia', '{"instagram": "https://instagram.com/ameliagarcia"}'::jsonb),
('{"en": "Harper Brown", "fr": "Harper Brown", "ar": "هاربر براون"}', '{"en": "Vintage and retro fashion enthusiast recreating classic styles from past decades.", "fr": "Passionnée de mode vintage et rétro recréant des styles classiques des décennies passées.", "ar": "شغوفة بالموضة القديمة والرترو تعيد إنشاء الأنماط الكلاسيكية من العقود الماضية."}', 'https://images.pexels.com/photos/7809000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Vintage Expert', 'Historical Fashion'], ARRAY['vintage', 'retro', 'costume'], true, 'https://example.com/instructor-harper', '{"instagram": "https://instagram.com/harperbrown", "pinterest": "https://pinterest.com/harpervintage"}'::jsonb),
('{"en": "Evelyn Miller", "fr": "Evelyn Miller", "ar": "إيفلين ميلر"}', '{"en": "Sustainable fashion advocate creating eco-friendly patterns with zero-waste techniques.", "fr": "Avocate de la mode durable créant des patrons écologiques avec des techniques zéro déchet.", "ar": "مؤيدة للأزياء المستدامة تنشئ أنماط صديقة للبيئة بتقنيات خالية من النفايات."}', 'https://images.pexels.com/photos/7810000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Sustainable Fashion Designer', 'Zero-Waste Expert'], ARRAY['sustainable', 'eco-friendly', 'organic'], true, 'https://example.com/instructor-evelyn', '{"instagram": "https://instagram.com/evelynmiller"}'::jsonb),
('{"en": "Abigail Lee", "fr": "Abigail Lee", "ar": "أبيجيل لي"}', '{"en": "Basics and essentials designer creating wardrobe staples and everyday patterns.", "fr": "Designer de basiques créant des essentiels de garde-robe et patrons du quotidien.", "ar": "مصممة أساسيات تنشئ قطع أساسية للخزانة وأنماط يومية."}', 'https://images.pexels.com/photos/7811000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Essentials Expert', 'Wardrobe Basics'], ARRAY['casual wear', 'basics', 'essentials'], false, 'https://example.com/instructor-abigail', '{"instagram": "https://instagram.com/abigaillee"}'::jsonb),
('{"en": "Emily Taylor", "fr": "Emily Taylor", "ar": "إميلي تايلور"}', '{"en": "Couture fashion designer creating high-fashion and avant-garde patterns.", "fr": "Designer haute couture créant des patrons de haute mode et avant-garde.", "ar": "مصممة أزياء راقية تنشئ أنماط أزياء عالية وطليعية."}', 'https://images.pexels.com/photos/7812000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Haute Couture Designer', 'Avant-Garde Artist'], ARRAY['couture', 'high fashion', 'avant-garde'], true, 'https://example.com/instructor-emily', '{"instagram": "https://instagram.com/emilytaylor"}'::jsonb),
('{"en": "Elizabeth Anderson", "fr": "Elizabeth Anderson", "ar": "إليزابيث أندرسون"}', '{"en": "Resort and swimwear designer creating beautiful beach and vacation wear.", "fr": "Designer de vêtements de plage créant des pièces magnifiques pour les vacances.", "ar": "مصممة ملابس المنتجعات والسباحة تنشئ ملابس شاطئ وإجازة جميلة."}', 'https://images.pexels.com/photos/7813000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Swimwear Specialist', 'Resort Wear Designer'], ARRAY['swimwear', 'resort wear', 'beachwear'], false, 'https://example.com/instructor-elizabeth', '{"instagram": "https://instagram.com/elizabethanderson"}'::jsonb),
('{"en": "Ava Thomas", "fr": "Ava Thomas", "ar": "آفا توماس"}', '{"en": "Professional workwear designer creating office-appropriate and career-oriented patterns.", "fr": "Designer de vêtements professionnels créant des patrons adaptés au bureau.", "ar": "مصممة ملابس عمل احترافية تنشئ أنماط مناسبة للمكتب والوظيفة."}', 'https://images.pexels.com/photos/7814000/pexels-photo.jpeg?auto=compress&cs=tinysrgb&w=200', ARRAY['Workwear Specialist', 'Professional Attire'], ARRAY['workwear', 'uniforms', 'professional'], true, 'https://example.com/instructor-ava', '{"instagram": "https://instagram.com/avathomas"}'::jsonb);
